// 2-2 고급웹프로그래밍/week10/11주차의 압축 파일/src/react_2/src/App.js
import { BrowserRouter, Route, Routes, Link } from "react-router-dom";

import index from "./Component/index";
import Introduction from "./Component/Introduction";
import Project from "./Component/Project";
import Contest from "./Component/Contest";
import Career from "./Component/Career";

import "./App.css";

function App() {
  return (
    <BrowserRouter>
      <header>
        김창복의 portfolio
        <br />
        "준비된 개발자"
      </header>

      <div className="container">
        <nav>
          <Link to={"/introduction"}>나의 소개</Link>
          <Link to={"/project"}>프로 젝트</Link>
          <Link to={"/contest"}>공 모 전 </Link>
          <Link to={"/career"}>나의 경력</Link>
        </nav>
        <main>
          <Routes>
            <Route path="/" Component={index} />
            <Route path="/introduction" Component={Introduction} />
            <Route path="/project" Component={Project} />
            <Route path="/contest" Component={Contest} />
            <Route path="/career" Component={Career} />
          </Routes>
        </main>
      </div>
      <footer>
        <i>
          Copyright 2023. 지은이 all rights reserved.
          <br />
          연락처 : 010-8906-3946
        </i>
      </footer>
    </BrowserRouter>
  );
}

export default App;

// 2-2 고급웹프로그래밍/week10/11주차의 압축 파일/src/vue_2/src/App.vue
<template>
  <div id ="index" >
    <header>
      김창복의 portfolio
      <br />
      "준비된 개발자"
    </header>
    
    <div id="container">
      <div id ="nav">
        <router-link class="link1" to="/introduction"> 나의 소개 </router-link>
        <router-link class="link1" to="/project"> 프로 젝트 </router-link>
        <router-link class="link1" to="/contest"> 공 모 전 </router-link>
        <router-link class="link1" to="/career"> 나의 경력 </router-link>
      </div>
     
      <div id = "main"> 
        <router-view /> 
      </div>
    </div>  
    
    <footer>
      Copyright 2023. 지은이 all rights reserved.
      <br />
      연락처 : 010-8906-3946
    </footer>
  </div>  
</template>

<style src="./App.css"> </style>
